extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_how_do_i_make_a_speaker_lights;
extern Lights1 castle_grounds_dl_f3d_material_lights;
extern Lights1 castle_grounds_dl_back_wall_lights;
extern u8 castle_grounds_dl_box_i8[];
extern u8 castle_grounds_dl_floor_ci4[];
extern u8 castle_grounds_dl_floor_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_tex1_ci4[];
extern u8 castle_grounds_dl_tex1_ci4_pal_rgba16[];
extern Vtx castle_grounds_dl_Plane_002_mesh_layer_1_vtx_0[492];
extern Gfx castle_grounds_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_002_mesh_layer_1_vtx_1[32];
extern Gfx castle_grounds_dl_Plane_002_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Plane_002_mesh_layer_1_vtx_2[10];
extern Gfx castle_grounds_dl_Plane_002_mesh_layer_1_tri_2[];
extern Gfx mat_castle_grounds_dl_how_do_i_make_a_speaker[];
extern Gfx mat_castle_grounds_dl_f3d_material[];
extern Gfx mat_revert_castle_grounds_dl_f3d_material[];
extern Gfx mat_castle_grounds_dl_back_wall[];
extern Gfx mat_revert_castle_grounds_dl_back_wall[];
extern Gfx castle_grounds_dl_Plane_002_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
