extern const GeoLayout bf_1_left[];
extern const GeoLayout bf_2_up[];
extern const GeoLayout bf_3_down[];
extern const GeoLayout bf_4_right[];
extern const GeoLayout bf_geo[];
extern Lights1 bf_neutral_lights;
extern Lights1 bf__1_LEFT_lights;
extern Lights1 bf__2_up_lights;
extern Lights1 bf__3_down_lights;
extern Lights1 bf__4_right_lights;
extern u8 bf__0_rgba16[];
extern u8 bf__1_rgba16[];
extern u8 bf__3_rgba32[];
extern u8 bf__4_rgba32[];
extern u8 bf__2_rgba16[];
extern Vtx bf_neutral_mesh_layer_5_vtx_0[756];
extern Gfx bf_neutral_mesh_layer_5_tri_0[];
extern Vtx bf_left_1_left_mesh_layer_5_vtx_0[764];
extern Gfx bf_left_1_left_mesh_layer_5_tri_0[];
extern Vtx bf_up_2_up_mesh_layer_5_vtx_0[1024];
extern Gfx bf_up_2_up_mesh_layer_5_tri_0[];
extern Vtx bf_down_3_down_mesh_layer_5_vtx_0[1024];
extern Gfx bf_down_3_down_mesh_layer_5_tri_0[];
extern Vtx bf_right_4_right_mesh_layer_5_vtx_0[772];
extern Gfx bf_right_4_right_mesh_layer_5_tri_0[];
extern Gfx mat_bf_neutral[];
extern Gfx mat_revert_bf_neutral[];
extern Gfx mat_bf__1_LEFT[];
extern Gfx mat_revert_bf__1_LEFT[];
extern Gfx mat_bf__2_up[];
extern Gfx mat_revert_bf__2_up[];
extern Gfx mat_bf__3_down[];
extern Gfx mat_revert_bf__3_down[];
extern Gfx mat_bf__4_right[];
extern Gfx mat_revert_bf__4_right[];
extern Gfx bf_neutral_mesh_layer_5[];
extern Gfx bf_left_1_left_mesh_layer_5[];
extern Gfx bf_up_2_up_mesh_layer_5[];
extern Gfx bf_down_3_down_mesh_layer_5[];
extern Gfx bf_right_4_right_mesh_layer_5[];
extern Gfx bf_material_revert_render_settings[];
